### ISSUE TITLE
Crashable with unending while loop

### ISSUE THREAD

**Issue by bend-n** [williamd1k0/gdscript-playground#20]

**Comment by williamd1k0** [comment]
I don't think it's a real issue on my end as the server is running in a container.
If you try to force an infinite loop, you'll get the following outcomes:
- The request will fail (because there is a timeout on the connection), and no response will be received (responses are not buffered);
- The server may crash due to OOM killer, but the container will restart automatically.

Anyway, I can set a configuration on the server to run godot with a timeout, so the request can complete with a response.

**Comment by bend-n** [comment]
The server seemed to take a while before it restarted though.

**Comment by williamd1k0** [comment]
I'm looking at the request logs and the server is putting all requests in a queue (and eventually failing due to connection timeout) while not terminating the infinite loop requests that were created before.
I'll try to fix it then.

**Comment by williamd1k0** [comment]
Done. I just fixed the DoS by adding a process timeout (default to 5s).
Code example to test:
```gdscript
extends Node

func _ready():
	var i = 0
	while true:
		print(i)
		i += 1
```

Thanks for reporting.
