### ISSUE TITLE
Update to Godot 4.x

### ISSUE THREAD

**Issue by KoBeWi** [williamd1k0/gdscript-playground#24]
The playground shows Godot 3.5.1. I think it should be updated to 4.0, or even 4.1 stable once it's out. Most people are already using Godot 4.

**Comment by williamd1k0** [comment]
I started working on it last year (https://github.com/williamd1k0/gdscript-cli/commit/4329a9f054ad30d14f5ba717e0f509e146cbaeb7). But since I don't have much free time, it's taking a bit too long.
Also, as I'm still using Godot 3.5, I want to support both, so I'll need to make changes to the server and UI.

**Comment by williamd1k0** [comment]
So I decided to drop Godot 3.x support for now, as the changes to support both versions would take a really long time.
Also, I noticed that visits increased after Unity did some dirty things :grimacing:, so keeping 3.x now would cause confusion for newcomers.
![image](https://github.com/williamd1k0/gdscript-playground/assets/10428035/c4673963-3aa4-4e7c-ad53-4dd71a8ec392)
